language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

branches:
  only:
    - tests
    - v.0.1.0

git:
  depth: 3

cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install babel babel-core babel-register babel-preset-es2015 mocha chai

script:
  - npm run ci

notifications:
  email:
    - artem.gurzhii@gmail.com
