language: node_js
node_js:
  - "0.10"
  - "0.12"

branches:
  only:
    - v.0.1.0

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install babel babel-core babel-register babel-preset-es2015 mocha chai

script:
  - npm run ci

notifications:
  email:
    - artem.gurzhii@gmail.com
