# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - gulpfile.babel.js
  - README.md
  - test
  - jsdoc.json
  - docs
  - assets/js/libs
  - assets/js/common.js
  - assets/js/modules
  - assets/css/1-tools
  - assets/css/2-modules
  - assets/css/main.sass
  - gulp
  - commands.sh


markdown_ext: md
encoding: utf-8


# Conversion
markdown: kramdown
highlighter: rouge
future: true


# Serving
host: localhost
port: 3000
baseurl: ""
# url: "artemgurzhii.github.io/conference"


# Outputting
permalink: /:title/
paginate: 1
paginate_path: /page/:num
timezone: America/New_York


# Plugins
gems:
  - jekyll-paginate
  - jekyll
  - kramdown
  - bundler
  - jekyll-feed


# Other
read_post: Continue Reading
prev_page: Previous Page
next_page: Next Page


# Links
logo: /assets/img/min/favicon.png
css: /assets/css/min/main.min.css
js: /assets/js/min/common.min.js


# Main
name: Conference
year: 2016


# Meta Tags
site_description: Programming conferences for front-end and back-end devlopers
site_title: Web Conferences
site_keywords: Front-end Back-end Conference CSS HTML JavaScript HTML5 CSS3 Ruby Jekyll
social_keywords: Conference Programming Icon Social JS JavaScript HTML CSS


# Social
author: Artem Gurzhii
email: gyga98@mail.ru
github: https://github.com/artemgurzhii
twiiter: https://twitter.com/ArtemGurzhii
facebook: https://facebook.com/artem.gurzhii


# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
