# main
name: Conference
title: conference
year: 2016

# social
author: Artem Gurzhii
email: artem.gurzhii@gmail.com
github_username: artemgurzhii
twitter_username: ArtemGurzhii
description: 'hellowovlsgasdg flodf dwdtn'

# Serving
detach: false
host: localhost
baseurl: ""
permalink: pretty
url: "http://localhost:3000/"

# Build settings
markdown: kramdown
future: true
exclude: ["node_modules", "gulpfile.babel.js", "package.json", "config.codekit", "data.json", "Gemfile", "Gemfile.lock", "LICENSE", "ToDo.txt", "assets/js/common.js", "assets/css/1-tools", "assets/css/2-modules"]

# Site settings
description: Conferences
timezone: America/New_York
encoding: "utf-8"

# Other
read_post: "Continue Reading"
prev_page: "Previous Page"
next_page: "Next Page"

# Gems - will require each of these gems automatically
gems: [jekyll-paginate, jekyll, kramdown, bundler]

# how much items on each page
paginate: 5
