name: Test
markdown: redcarpet
highlighter: rouge
description: Test
exclude: ["node_modules", "gulpfile.js", "package.json", "config.codekit", "bower_components"]
permalink: pretty
sass:
  sass_dir: css/min/main.min.css
  style: expanded
