# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - gulpfile.babel.js
  - README.md
  - test
  - jsdoc.json
  - docs
  - assets/js/libs
  - assets/js/common.js
  - assets/js/modules
  - assets/css/1-tools
  - assets/css/2-modules
  - assets/css/main.sass
  - gulp
  - commands.sh

markdown_ext: md
encoding: utf-8

# Conversion
markdown: kramdown
highlighter: rouge
future: true

# Serving
host: localhost
port: 3000
baseurl: "http://artemgurzhii.github.io/jekyll-theme/"
url: "http://artemgurzhii.github.io/jekyll-theme/"

# Outputting
permalink: /:title/
paginate: 1
paginate_path: /page/:num
timezone: America/New_York

# Plugins
gems:
  - jekyll-paginate
  - jekyll
  - kramdown
  - bundler
  - jekyll-feed

# Other
read_post: Continue Reading
prev_page: Previous Page
next_page: Next Page


# Links
logo: /assets/img/min/favicon.png
css: /assets/css/min/main.min.css
js: /assets/js/min/common.min.js

# Main
name: Conference
year: 2016

# Meta Tags
site_description: Simple Jekyll theme
site_title: Jekyll theme
site_keywords: Front-end Back-end CSS HTML JavaScript HTML5 CSS3 Ruby Jekyll
social_keywords: Programming Jekyll Ruby JS JavaScript HTML CSS

# Social
author: Artem Gurzhii
email: artemgurzhii@gmail.com
github: https://github.com/artemgurzhii

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
