# main
name: "Conference"
title: "conference"
year: 2016
description: "Conferences"
timezone: "America/New_York"
encoding: "utf-8"

# Meta Tags
site_description: "Programming conferences for front-end and back-end devlopers"
site_title: "Web Conferences"
site_keywords: "Front-end Back-end Conference CSS HTML JavaScript HTML5 CSS3 Ruby Jekyll"

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# social
author: "Artem Gurzhii"
email: "gyga98@mail.ru"

# Server
host: localhost
port: 3000
baseurl: "http://artemgurzhii.github.io/conference/"
url: "http://artemgurzhii.github.io/conference/"

# Future Posts
future: true

# Build settings
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "node_modules",
  "package.json",
  "gulpfile.babel.js",
  "data/conferences.json",
  "README.md",
  "test",
  "jsdoc.json",
  "docs",
  "assets/js/libs",
  "assets/js/common.js",
  "assets/js/modules",
  "assets/css/1-tools",
  "assets/css/2-modules",
  "assets/css/main.sass"
]

# Gems - will require each of these gems automatically
gems:
  - jekyll-paginate
  - jekyll
  - kramdown
  - bundler
  - jekyll-sitemap

# how much items on each page
paginate: 3

# Other
read_post: "Continue Reading"
prev_page: "Previous Page"
next_page: "Next Page"
